name: Sample CDK deployment in AWS Account
env:
  AWS_REGION: "eu-central-1"

on: [push, workflow_dispatch]
jobs:
  aws_cdk:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.IAMROLE_GITHUB }}
          role-session-name: GitHub-Action-Role
          aws-region: ${{ env.AWS_REGION }}

      - name: Install cdk
        run: yarn add aws-cdk
      - name: build project
        run: npx projen build
      - name: Deploy stack
        run: npx cdk deploy --all --require-approval never